plugins {
    id 'java'
    id 'application'
}

group = 'org.example'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation project (':ChatModel')
    implementation project (':ChatService')
    implementation project (':ChatNetworking')
}
application{
    mainClass='StartRpcClient'
}
test {
    useJUnitPlatform()
}