plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

group = 'org.example'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation project (':ChatModel')
    implementation project (':ChatService')
    implementation project (':ChatNetworking')
    implementation project (':ChatPersistence')
    implementation project (':ChatServer')

    implementation 'org.openjfx:javafx-controls:23.0.1'
    implementation 'org.openjfx:javafx-fxml:23.0.1'
    implementation 'org.openjfx:javafx-base:23.0.1'
    implementation 'org.openjfx:javafx-graphics:23.0.1'

    runtimeOnly 'org.openjfx:javafx-controls:23.0.1:win'
    runtimeOnly 'org.openjfx:javafx-fxml:23.0.1:win'
    runtimeOnly 'org.openjfx:javafx-base:23.0.1:win'
    runtimeOnly 'org.openjfx:javafx-graphics:23.0.1:win'

    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-api:2.23.1'
}

javafx {
    version = "23.0.1"
    modules = ['javafx.controls', 'javafx.fxml']
}

application{
    mainClass='StartRpcClientFX'
}
test {
    useJUnitPlatform()
}